services:
  postgres:
    image: postgres:16
    container_name: rastreamento-db
    environment:
      POSTGRES_DB: rastreamento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: rastreamento-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/rastreamento
      DB_USERNAME: postgres
      DB_PASSWORD: 123
    ports:
      - "8080:8080"

volumes:
  postgres_data: